apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001  # Correctly specified for a NodePort service
  type: NodePort  # Must specify type NodePort to use nodePort
  
  ---
  
  apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:  # Correct spelling of 'labels'
    app: my-app
spec:
  containers:
    - name: my-container
      image: nginx
      ports:
        - containerPort: 80  # Correct field name: containerPort
      
